[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.17.0"

# Custom caching to speed up builds
[build.cache]
paths = [
  "node_modules/**/*",  # Cache node_modules between builds
  ".cache/**/*",        # Cache Vue CLI's cache (if it exists)
  "public/**/*",        # Cache public folder (optional)
  "go/pkg/mod",         # Cache Go modules (if you're using Go)
  ".cache/go-build"     # Cache Go build artifacts (optional)
]
