[build]
  publish = "dist"  # Vue builds to the `dist` directory by default
  command = "npm run build"
  environment = { NODE_VERSION = "18.17.0" }

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.17.0"

# Custom caching to speed up builds
[build.cache]
paths = [
  "node_modules/**/*",  # Cache node_modules between builds
  "public/**/*",        # Cache the public folder (optional)
  ".cache/**/*",        # If using vue-cli-service or any custom cache directory
  "dist/**/*",          # Cache build output for faster redeploys (optional)
  "go/pkg/mod",         # Cache Go modules
  ".cache/go-build"     # Cache Go build artifacts (optional)
]